version: '3.8'
services:
  event-bus:
    build: event-bus/.
    ports:
      - "5000:5000"
  manage-user-state:
    build: manage-user-state/.
    ports:
      - "4003:4003"
  posts:
    build: posts/.
    ports:
      - "4004:4004"
    depends_on:
      - "posts-db"
  posts-db:
    build: posts-db/.
    ports:
      - "4010:4010"
    depends_on:
      - "database"
  auth:
    build: auth/.
    ports:
      - "4000:4000"
  likes:
    build: likes/.
    ports:
      - "4006:4006"
    depends_on:
      - "likes-db"
  likes-db:
    build: likes-db/.
    ports:
      - "4009:4009"
    depends_on:
      - "database"
  validate-account:
    build: validate-account/.
    ports:
      - "4002:4002"
  create-account:
    build: create-account/.
    ports:
      - "4001:4001"
    depends_on:
      - "users-db"
  users-db:
    build: users-db/.
    ports:
      - "4011:4011"
    depends_on:
      - "database"
  comments:
    build: comments/.
    ports:
      - "4005:4005"
    depends_on:
      - "comments-db"
  comments-db:
    build: comments-db/.
    ports:
      - "4008:4008" 
    depends_on:
      - "database"
  database:
    build: databases/database/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data   

volumes:
  pg_data: null
